name:                hagia
version:             0.1.0.0
github:              "radrow/hagia"
license:             MIT
author:              "Radosław Rowicki"
maintainer:          "ikciwor [fancy a] ymail [dot] [short for commercial]"
copyright:           "Radosław Rowicki"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Property checker for Sophia smart contract language
category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/radrow/hagia#readme>

dependencies:
- base >= 4.7 && < 5
- network
- text

library:
  source-dirs: src
  dependencies:
  - mtl
  - containers
  - megaparsec

executables:
  hagia-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hagia

#tests:
#  hagia-test:
#    main:                Spec.hs
#    source-dirs:         test
#    ghc-options:
#    - -threaded
#    - -rtsopts
#    - -with-rtsopts=-N
#    dependencies:
#    - hagia
#    - quickcheck
